name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore -p:EnableWindowsTargeting=true

    - name: Build
      run: dotnet build --no-restore -c Release -p:EnableWindowsTargeting=true

    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal -p:EnableWindowsTargeting=true

    - name: Publish (WPF self-contained single-file)
      run: >
        dotnet publish ./RPMulate.csproj
        -c Release
        -r win-x64
        --self-contained true
        -p:PublishSingleFile=true
        -p:EnableWindowsTargeting=true
        -p:IncludeNativeLibrariesForSelfExtract=true
        -o publish

    - name: Upload published app
      uses: actions/upload-artifact@v4
      with:
        name: RPMulate
        path: publish/**
